Controllers/ClassRoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OnyxPlataform.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;


namespace OnyxPlataform.Controllers
{
    public class ClassRoomController : Controller
    {
        //readonly data
        public readonly AplicationDbContext _Context;
        //constructores
        public ClassRoomController(AplicationDbContext context){
            _Context=context;
        }

        //index
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Detalle()
        {
            return View("Detalle");
        }

        //creacion de un classroom
        //funcion que crea los datos
        [HttpGet]
        public IActionResult Create(string ID)
        {
            ClassRoom temp=new ClassRoom();
            temp.UserDataId=ID;
            Random random= new Random();
            temp.ClassRoomId=Convert.ToString(random.Next(1,1000)+random.Next(1,12200));

            return View("Create", temp);
        }
        //funcion que agrega el ClassRoomo a la base de datos
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ClassRoom temp)
        {
            if(ModelState.IsValid){
                _Context.ClassRoomList.Add(temp);
               await  _Context.SaveChangesAsync();
            }
            return View("Index",await _Context.ClassRoomList.ToListAsync());
        }
        //funcion que edita un classroom
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if(id==null){
                return NotFound();
            }
            ClassRoom temp=await _Context.ClassRoomList.FindAsync(id);
            if(temp==null){
                return NotFound();
            }
            return View(temp);
        }
        //funcion que edita en post los datos
         [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id,    ClassRoom temp)
        {
            if(id==null){
                return NotFound();
            }
            if(ModelState.IsValid){
                try{
                    _Context.Update(temp);
                }catch(DbUpdateConcurrencyException){
                    throw;
                }
                return View("Index",await _Context.ClassRoomList.ToListAsync());
            }
            return View("Index",await _Context.ClassRoomList.ToListAsync());
            
        }
        //funcion que elimina los datos
         public async Task<IActionResult> Delete(string id)
        {
            ClassRoom temp= await _Context.ClassRoomList.FindAsync(id);
            if(temp==null){
                return NotFound();
            }
            _Context.Remove(temp);
           await _Context.SaveChangesAsync();
            
            return View("Index",await _Context.ClassRoomList.ToListAsync());
        }
    }
}

Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OnyxPlataform.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace OnyxPlataform.Controllers
{
    public class StoreController : Controller
    {
        //readonlydata
        public readonly AplicationDbContext _Context;
        //constructor del controlador
        public StoreController(AplicationDbContext context){
            _Context=context;
        }

        public async Task<IActionResult> Index()
        {
            var list=await _Context.StoreList.ToListAsync();
            return View(list);
        }

        public IActionResult store()
        {
            return View();
        }

        //vista de una tyienda en especiofico
        public async Task<IActionResult> ShowStore(string Id)
        {
            Store temp=await _Context.StoreList.FindAsync(Id);
            List<Catalogue> list=new List<Catalogue>();
            foreach (var item in _Context.CatalogueList)
            {
                if(item.StoreId==temp.StoreId){
                    list.Add(item);
                }
                ViewBag.productList=list;
            }
            if(ViewBag.productList==null){
                return NotFound();
            }
            return View(temp);
        }
        //creacion de una Tienda
        [Authorize]
        [HttpGet]
        public IActionResult Create(string ID)
        {
            Store temp=new Store();
            temp.UserDataId=ID;
            Random random= new Random();
            temp.StoreId=Convert.ToString(random.Next(1,1000)+random.Next(1,12200));

            return View("Create", temp);
        }
        //funcion que agrega el Storeo a la base de datos
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Store temp)
        {
            if(ModelState.IsValid){
                _Context.StoreList.Add(temp);
               await  _Context.SaveChangesAsync();
            }
            return View("Index",await _Context.StoreList.ToListAsync());
        }

        //funcion que edita una tienda
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(string id)
        {
            if(id==null){
                return NotFound();
            }
            Store temp=await _Context.StoreList.FindAsync(id);
            if(temp==null){
                return NotFound();
            }
            return View(temp);
        }
        //funcion que edita en post los datos
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, Store temp)
        {
            if(id==null){
                return NotFound();
            }
            if(ModelState.IsValid){
                try{
                    _Context.Update(temp);
                }catch(DbUpdateConcurrencyException){
                    throw;
                }
                return View("Index",await _Context.StoreList.ToListAsync());
            }
            return View("Index",await _Context.StoreList.ToListAsync());
            
        }
        //funcion que elimina un tienda
        [Authorize]
        public async Task<IActionResult> Delete(string id)
        {
            Store temp= await _Context.StoreList.FindAsync(id);
            if(temp==null){
                return NotFound();
            }
            _Context.Remove(temp);
           await _Context.SaveChangesAsync();
            
            return View("Index",await _Context.StoreList.ToListAsync());
        }
    
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnyxPlataform </title>

    <environment include="Development">
       <partial name="_StylesPartial">
        
    </environment>
</head>
<body id="home" class="wide">
   
    <!-- WRAPPER -->
    <div class="wrapper"> 

    <!-- Popup: Shopping cart items -->
    <div class="modal fade popup-cart" id="popup-cart" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="container">
                <div class="cart-items">
                    <div class="cart-items-inner">
                        <div class="media">
                            <a class="pull-left" href="#"><img class="media-object item-image" src="assets/img/preview/items/img1.jpg" alt=""></a>
                            <p class="pull-right item-price">$450.00</p>
                            <div class="media-body">
                                <h4 class="media-heading item-title"><a href="#"> Mouse Gamer </a></h4>
                                <p class="item-desc">Mouse gamer logitech</p>
                            </div>
                        </div>
                        <div class="media">
                            <p class="pull-right item-price">C$450.00</p>
                            <div class="media-body">
                                <h4 class="media-heading item-title summary">Subtotal</h4>
                            </div>
                        </div>
                        <div class="media">
                            <div class="media-body">
                                <div>
                                    <a href="#" class="btn btn-theme btn-theme-dark" data-dismiss="modal">Cerrar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /Popup: Shopping cart items -->

        <!-- Header top bar -->
        <div class="top-bar">
            <div class="container">
                <div class="top-bar-left">
                    <ul class="list-inline">
                        <partial name="_LoginPartial"/>
                    </ul>
                </div>
                <div class="top-bar-right">
                    <ul class="list-inline">
                        <li class="hidden-xs"><a href="about.html">Acerca de</a></li>
                        <li class="hidden-xs"><a href="blog.html"><i class="fa fa-facebook"></i> Siguenos en Facebook!</a></li>                             
                        <li class="hidden-xs"><a href="accountinformation.html">Mi Cuenta</a></li>
                        <li class="hidden-xs"><a href="contact.html"><i class="fa fa-edit"></i> Contacto</a></li>
                        <li class="hidden-xs"><a href="faq.html">FAQ</a></li>
                        <li class="hidden-xs"><a href="wishlist.html"><i class="fa fa-heart"></i> Mi Lista de Deseos</a></li>
                        <li class="dropdown currency">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">C$ Cordoba<i class="fa fa-angle-down"></i></a>
                            <ul role="menu" class="dropdown-menu">
                                <li><a href="#">€ EURO</a></li>
                                <li><a href="#">$ Dolar</a></li>
                            </ul>
                        </li>
                        <li class="dropdown flags">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="assets/img/flag.gif" alt=""/> Es<i class="fa fa-angle-down"></i></a>
                            <ul role="menu" class="dropdown-menu">
                                <li><a href="#"><img src="assets/img/flag.gif" alt=""/> Eng</a></li>
                                <li><a href="#"><img src="assets/img/flag.gif" alt=""/> Eng</a></li>
                                <li><a href="#"><img src="assets/img/flag.gif" alt=""/> Eng</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /Header top bar -->

            <!-- HEADER -->
            <header class="header fixed">
                <div class="header-wrapper">
                    <div class="container">

                        <!-- Logo -->
                        <div class="logo">
                            <a href="index.html"><img src="~/assets/img/logo.png"/></a>
                        </div>
                        <!-- /Logo -->

                        <!-- Header search -->
                        <div class="header-search">
                            <input class="form-control" type="text" placeholder="HOLA!, que busco por ti hoy?"/>
                            <button><i class="fa fa-search"></i></button>
                        </div>
                        <!-- /Header search -->

                        <!-- Header shopping cart -->
                        <div class="header-cart">
                            <div class="cart-wrapper">
                                <a href="wishlist.html" class="btn btn-theme-transparent hidden-xs hidden-sm"><i class="fa fa-heart"></i></a>
                                <a href="compare-products.html" class="btn btn-theme-transparent hidden-xs hidden-sm"><i class="fa fa-exchange"></i></a>
                                <a href="#" class="btn btn-theme-transparent" data-toggle="modal" data-target="#popup-cart"><i class="fa fa-shopping-cart"></i> <span class="hidden-xs"> 0 producto(s) - C$0.00 </span> <i class="fa fa-angle-down"></i></a>
                                <!-- Mobile menu toggle button -->
                                <a href="#" class="menu-toggle btn btn-theme-transparent"><i class="fa fa-bars"></i></a>
                                <!-- /Mobile menu toggle button -->
                            </div>
                        </div>
                        <!-- Header shopping cart -->

                    </div>
                </div>
                <div class="navigation-wrapper">
                    <div class="container">
                        <!-- Navigation -->
                        <nav class="navigation closed clearfix">
                            <a href="#" class="menu-toggle-close btn"><i class="fa fa-times"></i></a>
                            <ul class="nav sf-menu">
                            
                                <li><a asp-controller="Home" asp-action="Index"><i class="fa fa-home"></i>Inicio</a></li>
                                <li><a asp-controller="ClassRoom" asp-action="Index"><i class="fa fa-edit"></i> Sala de Clases </a></li>
                                <li><a asp-controller="Store" asp-action="Index"><i class="fa fa-home"></i> Tienda </a></li>
                                <li><a asp-controller="Store" asp-action="Create"><i class="fa fa-edit"></i> Crea tu tienda! </a></li>
                            </ul>
                        </nav>
                        <!-- /Navigation -->
                    </div>
                </div>
            </header>
            <!-- /HEADER -->

    
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <!-- FOOTER -->
            <footer class="footer">
                <div class="footer-widgets">
                    <div class="container">
                        <div class="row">

                            <div class="col-md-3">
                                <div class="widget">
                                    <h4 class="widget-title">Un Poco de ONYX</h4>
                                    <p>ONYX ha venido para quedarse. el comercio nicaraguense en tus manos. Se a creado a ONYX para satisfacer tus necesidades de compra de productos</p>
                                    <ul class="social-icons">
                                        <li><a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li>
                                        <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                                        <li><a href="#" class="instagram"><i class="fa fa-instagram"></i></a></li>
                                        <li><a href="#" class="pinterest"><i class="fa fa-pinterest"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="widget">
                                    <h4 class="widget-title">Ultimas Noticias</h4>
                                    <p>ONYX es lanzado al mercado muy pronto.</p>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="widget widget-categories">
                                    <h4 class="widget-title">Informacion</h4>
                                    <ul>
                                        <li><a href="#">Acerca de Nosotros</a></li>
                                        <li><a href="#">Informacion de las Entregas</a></li>
                                        <li><a href="#">Contactanos</a></li>
                                        <li><a href="#">Terminos Y condiciones</a></li>
                                        <li><a href="#">Politicas de Privacidad</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="widget widget-tag-cloud">
                                    <h4 class="widget-title">Tags de Busqueda en ONYX</h4>
                                    <ul>
                                        <li><a href="#">Moda</a></li>
                                        <li><a href="#">Jeans</a></li>
                                        <li><a href="#">Top Ventas</a></li>
                                        <li><a href="#">E commerce hoy en dia</a></li>
                                        <li><a href="#">Ofertas de Solo hoy</a></li>
                                        <li><a href="#">Suplementos</a></li>
                                        <li><a href="#">Tiendas</a></li>
                                        <li><a href="#">Temas</a></li>
                                        <li><a href="#">Website</a></li>
                                        <li><a href="#">Casa</a></li>
                                        <li><a href="#">autopartes</a></li>
                                    </ul>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="footer-meta">
                    <div class="container">
                        <div class="row">

                            <div class="col-sm-6">
                                <div class="copyright">Copyright 2019 ONYX   |   All Rights Reserved   |   Developed by ONYXTEAM</div>
                            </div>
                            <div class="col-sm-6">
                                <div class="payments">
                                    <ul>
                                        <li><img src="assets/img/preview/payments/visa.jpg" alt=""/></li>
                                        <li><img src="assets/img/preview/payments/mastercard.jpg" alt=""/></li>
                                        <li><img src="assets/img/preview/payments/paypal.jpg" alt=""/></li>
                                        <li><img src="assets/img/preview/payments/american-express.jpg" alt=""/></li>
                                        <li><img src="assets/img/preview/payments/visa-electron.jpg" alt=""/></li>
                                        <li><img src="assets/img/preview/payments/maestro.jpg" alt=""/></li>
                                    </ul>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </footer>
            <!-- /FOOTER -->


   

    @RenderSection("Scripts", required: false)
</body>

    <environment include="Development">
       <partial name="_ValidationScriptsPartial">
    </environment>
    
</html>

Views/Shared/_StylesPartial.cshtml
<environment include="Development">

        <link rel="shortcut icon" href="assets/icon/favicon.ico">

        <!-- CSS Global -->
        <link href="~/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="~/assets/plugins/bootstrap-select/css/bootstrap-select.min.css" rel="stylesheet">
        <link href="~/assets/plugins/fontawesome/css/font-awesome.min.css" rel="stylesheet">
        <link href="~/assets/plugins/prettyphoto/css/prettyPhoto.css" rel="stylesheet">
        <link href="~/assets/plugins/owl-carousel2/assets/owl.carousel.min.css" rel="stylesheet">
        <link href="~/assets/plugins/owl-carousel2/assets/owl.theme.default.min.css" rel="stylesheet">
        <link href="~/assets/plugins/animate/animate.min.css" rel="stylesheet">
        <!-- Theme CSS -->
        <link href="~/assets/css/theme.css" rel="stylesheet">
        
        <!-- <link href="~/assets/css/theme-yellow-1.css" rel="stylesheet" id="theme-config-link"> -->

        <!-- Head Libs -->
        <script src="~/assets/plugins/modernizr.custom.js"></script>


</environment>