Models/Catalogue.cs
using System;
using OnyxPlataform.Models;
namespace OnyxPlataform.Models
{
    //definicion de la clase catalogo
    public class Catalogue
    {
        public string CatalogueID{get;set;}
        //definicion de la llava foranea
        public string StoreId{get;set;}
        
        public string CatalogueProductName{get;set;}
        public string CatalogueProductModel{get;set;}
        public string CatalogueProductBrand{get;set;}
        public string CatalogueProductBuilder{get;set;}
        public string CatalogueProductType{get;set;}
        public string CatalogueProductDescription{get;set;}
        //referencia a un o0bjeto de la clase store
        public Store store{get;set;}
    }
}

Controllers/CatalogueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OnyxPlataform.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace OnyxPlataform.Controllers
{
    public class CatalogueController : Controller
    {
        //dato readonly
        public readonly AplicationDbContext _Context;
        //constructor
        public CatalogueController(AplicationDbContext Context){
            _Context=Context;
        }
        //index de los controladores
        public async Task<IActionResult> Index()
        {
            var list= await _Context.CatalogueList.ToListAsync();
            return View(list);
        }
        //funcion que crea los datos
        [HttpGet]
        public IActionResult Create(string ID)
        {
            Catalogue temp=new Catalogue();
            temp.CatalogueID=ID;
            Random random= new Random();
            temp.CatalogueID=Convert.ToString(random.Next(1,1000)+random.Next(1,12200));

            return View("Create", temp);
        }
        //funcion que agrega el Catalogueo a la base de datos
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Catalogue temp)
        {
            if(ModelState.IsValid){
                _Context.CatalogueList.Add(temp);
               await  _Context.SaveChangesAsync();
            }
            return View("Index",await _Context.CatalogueList.ToListAsync());
        }
         //funcion que edita una tienda
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if(id==null){
                return NotFound();
            }
            Catalogue temp=await _Context.CatalogueList.FindAsync(id);
            if(temp==null){
                return NotFound();
            }
            return View(temp);
        }
        //funcion que edita en post los datos
         [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, Catalogue temp)
        {
            if(id==null){
                return NotFound();
            }
            if(ModelState.IsValid){
                try{
                    _Context.Update(temp);
                }catch(DbUpdateConcurrencyException){
                    throw;
                }
                return View("Index",await _Context.CatalogueList.ToListAsync());
            }
            return View("Index",await _Context.CatalogueList.ToListAsync());
            
        }
        //funcion que elimina un Calogo
         public async Task<IActionResult> Delete(string id)
        {
            Catalogue temp= await _Context.CatalogueList.FindAsync(id);
            if(temp==null){
                return NotFound();
            }
            _Context.Remove(temp);
           await _Context.SaveChangesAsync();
            
            return View("Index",await _Context.CatalogueList.ToListAsync());
        }
    }
}

Views/Catalogue/Create.cshtml
@model OnyxPlataform.Models.Catalogue
<div class=" card col-md-4 offset-md-4 p-0 mt-2">
    <h3 class="card-header">
        Creando Tus Productos
    </h3>
    <div class="card-body">
        <form asp-controller="Catalogue" asp-action="Create" method="POST">
            <input type="hidden" asp-for="@Model.CatalogueID" value="@Model.CatalogueID">
            <input  type="hidden" asp-for="@Model.StoreId" value="@Model.StoreId">
            <div class="form-group">
                <label for="">Escribe el Nombre de tu Producto</label>
                <input  class="form-control" asp-for="@Model.CatalogueProductName" id="">
            </div>
                <div class="form-group">
                <label for="">Modelo? dejalo vacio si tu prodcuto no cuenta con uno</label>
                <input  class="form-control" asp-for="@Model.CatalogueProductModel" id="">
            </div>
                <div class="form-group">
                <label for="">Describe tu producto</label>
                <input  class="form-control" asp-for="@Model.CatalogueProductDescription" id="">
            </div>
                <div class="form-group">
                <label for="">Tipo de Producto</label>
                <input  class="form-control" asp-for="@Model.CatalogueProductType" id="">
            </div>
                <div class="form-group">
                <label for="">¿Alguien ha fabricado el producto? especificalo</label>
                <input  class="form-control" asp-for="@Model.CatalogueProductBuilder" id="">
            </div>
            <div class="form-group">
                <label for="">Agrega Una Imagen de tu producto</label>
                <input type="file">
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
</div>

Views/Catalogue/Edit.cshtml
@model OnyxPlataform.Models.Catalogue
<div class=" card col-md-4 offset-md-4 p-0 mt-2">
    <h3 class="card-header">
        Creando Tus Productos
    </h3>
    <div class="card-body">
        <form asp-controller="Catalogue" asp-action="Create" method="POST">
            <input type="hidden" asp-for="@Model.CatalogueID" value="@Model.CatalogueID">
            <input  type="hidden" asp-for="@Model.StoreId" value="@Model.StoreId">
            <div class="form-group">
                <label for="">Escribe el Nombre de tu Producto</label>
                <input  class="form-control" asp-for="@Model.CatalogueProductName" id="" value="@Model.CatalogueProductName">
            </div>
                <div class="form-group">
                <label for="">Modelo</label>
                <input  class="form-control" asp-for="@Model.CatalogueProductModel" id="" value="@Model.CatalogueProductModel">
            </div>
                <div class="form-group">
                <label for="">Descripcion</label>
                <input  class="form-control" asp-for="@Model.CatalogueProductDescription" id="" value="@Model.CatalogueProductDescription">
            </div>
                <div class="form-group">
                <label for="">Tipo de Producto</label>
                <input  class="form-control" asp-for="@Model.CatalogueProductType" id="" value="@Model.CatalogueProductType">
            </div>
                <div class="form-group">
                <label for="">Fabricante</label>
                <input  class="form-control" asp-for="@Model.CatalogueProductBuilder" id="" value="@Model.CatalogueProductBuilder">
            </div>
            <div class="form-group">
                <label for="">Imagen de tu producto</label>
                <input type="file">
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
</div>